#!/bin/bash

echo "Starting nginx_acmetool container"

ACMESTATEDIR=/var/lib/acme
RESPONSEFILE=$ACMESTATEDIR/conf/responses

if [ -z "$NAMES" ]; then
  echo "Variable NAMES has to be set"
  exit
fi

if [ -z "$EMAIL" ]; then
  echo "Variable EMAIL has to be set"
  exit
fi

if [ ! -f $RESPONSEFILE ]; then
  echo "Responsefile does not exist writing it"

  mkdir -p $ACMESTATEDIR/conf
  cat > $RESPONSEFILE <<- EOM
"acme-enter-email": "$EMAIL"
"acme-agreement:https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf": true
"acmetool-quickstart-choose-server": https://acme-staging.api.letsencrypt.org/directory
"acmetool-quickstart-choose-method": webroot
"acmetool-quickstart-webroot-path": "/var/run/acme/acme-challenge"
"acmetool-quickstart-complete": true
"acmetool-quickstart-install-cronjob": false
"acmetool-quickstart-install-haproxy-script": false
"acmetool-quickstart-install-redirector-systemd": false
"acmetool-quickstart-key-type": ecdsa
"acmetool-quickstart-rsa-key-size": 4096
"acmetool-quickstart-ecdsa-curve": nistp256
EOM
fi

echo Starting nginx with intermediate acmetool config
nginx -c /nginx-acmetool.conf
sleep 2

echo Executing acmetool want $NAMES
acmetool want $NAMES

echo Killing intermediate nginx
kill $(cat /var/run/nginx.pid)

echo Starting cron service
service cron start

echo Starting nginx
nginx -g "daemon off;"
